version: '3.8'

services:
  cto-supervisor:
    build: ./cto-supervisor
    container_name: cto-supervisor
    environment:
      - GITHUB_TOKEN=${GITHUB_CTO_TOKEN}
      - DB_CTO_USERNAME=cto_supervisor
      - DB_CTO_PASSWORD=${DB_CTO_PASSWORD}
      - STRICT_MODE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    networks:
      - cto-network
    restart: unless-stopped

  code-auditor:
    image: code-auditor:latest
    container_name: code-auditor
    depends_on:
      - cto-supervisor
    environment:
      - AUDIT_LEVEL=strict
      - SUPERVISOR_URL=http://cto-supervisor:8080
    volumes:
      - ./code:/code
      - ./audit-results:/results
    networks:
      - cto-network
    restart: unless-stopped

  postgres-cto:
    image: postgres:15
    container_name: postgres-cto
    environment:
      - POSTGRES_USER=cto_supervisor
      - POSTGRES_PASSWORD=${DB_CTO_PASSWORD}
      - POSTGRES_DB=cto_supervision
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database_supervision.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cto-network
    restart: unless-stopped

networks:
  cto-network:
    driver: bridge

volumes:
  postgres-data:

